# Dependabot configuration file
# See: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable npm dependency updates
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    # Apply our exact versioning strategy
    versioning-strategy: "lockfile-only"
    # Limit the number of open PRs to avoid overwhelming
    open-pull-requests-limit: 5
    # Add specific reviewers and labels
    labels:
      - "dependencies"
      - "npm"
    # Group updates to reduce PR noise
    groups:
      dev-dependencies:
        patterns:
          - "@types/*"
          - "eslint*"
          - "*-loader"
          - "jest*"
          - "@testing-library/*"
        update-types:
          - "minor"
          - "patch"
      typescript-ecosystem:
        patterns:
          - "typescript"
          - "ts-*"
        update-types:
          - "minor"
          - "patch"
      react-ecosystem:
        patterns:
          - "react*"
          - "next*"
        update-types:
          - "patch"
    # Security updates should always be separate
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Enable GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "ci"
      include: "scope" 