name: Lint Code

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['main', 'develop']
  workflow_dispatch:

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Lint JavaScript/TypeScript
        run: npm run lint || (echo "Linting failed, please fix the issues" && exit 1)
      
      - name: Check formatting with Prettier
        run: npx prettier --check "**/*.{js,ts,tsx,jsx,json,css,md}" || (echo "Formatting check failed" && exit 1)
      
      - name: Validate workflow files
        run: |
          for file in .github/workflows/*.yml; do
            echo "Validating $file"
            npx actionlint "$file" || exit 1
          done
      
      - name: Docker lint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          
      - name: Docker dev lint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile.dev
          
      - name: Docker test lint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile.test
      
      - name: Validate container-structure-test
        run: |
          if [ -f "container-structure-test.yaml" ]; then
            echo "Validating container-structure-test.yaml..."
            wget -q -O /tmp/container-structure-test https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64 && \
            chmod +x /tmp/container-structure-test && \
            /tmp/container-structure-test validate --config container-structure-test.yaml || exit 1
            echo "container-structure-test.yaml is valid"
          else
            echo "container-structure-test.yaml not found, skipping validation"
          fi
      
      # Add a check for TypeScript types
      - name: TypeScript check
        run: npm run typecheck || (echo "TypeScript check failed" && exit 1)
        
      - name: Comment on PR
        if: github.event_name == 'pull_request' && failure()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '⚠️ Linting failed! Please check the workflow logs for details and fix the issues.'
            }) 